services:
  mysql:
    container_name: mysql_docker_instance
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'sauki123'
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin_docker_instance
    restart: always
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql:3306
volumes:
  mysql-data:
