services:
  rabbitmq:
    container_name: rabbitmq_docker_instance
    restart: always
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
volumes:
  rabbitmq-data:
  rabbitmq-log:
